language: minimal

addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-luatex
    - tex4ht
    - texlive-fonts-recommended
    - lmodern
    - texlive-lang-french
    - ghostscript
    - imagemagick
    - netpbm
    - tidy

script:
  - make dist
